### ISSUE TITLE
Foundations > 04-chaining-selectors : Add details about the height:auto effect in solution.css 

### ISSUE THREAD

**Issue by PerseveranceX** [TheOdinProject/css-exercises#150]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the enhancement :**

In the chaining selectors lesson, it's required from the learner to set the height to auto so the image keeps it's aspect ratio (proportions), but the height is automatically set to auto by the browser.

**Why provide more details in the solution?:** The learner can become confused of what he/she should do if the aspect ratio is already as requested.

**Suggested improvement**: When the learner looks into the solution it would be better to explain that height: auto; adjusts the height to preserve the original aspect ratio of the image, and that the image square aspect ratio was preserved even without writing height: auto; in the css because the height is automatically set to auto by the browser.

**Example**
```css
.avatar.proportioned {
  width: 300px;
  height: auto;
  /* 
     Setting the height property to auto tells the browser to adjust the height of the image
     to preserve the proportions (aspect ratio) of it,
     (e.g. If the the proportions of the image is 1:2 (width:height), and the width is set to 100px,
     then the height will be adjusted to 200px automatically.
  */
  /*
     The proportions of the image is preserved automatically event without typing height: auto;,
     because height is automatically set to auto by the browser.
  */
}
```
**2. Acceptance Criteria:**

- [x] A comment in solution.css that explains to the learner what height: auto; does, and why it's effect was applied even when we didn't write it in the css;
